x-app-service: &app-service
  build: .
  image: graphrag-demo-app:py312
  container_name: app
  command: ["streamlit", "run", "app.py"]
  volumes:
    - .:/app
  env_file:
    - .env
  environment:
    - TZ=Asia/Tokyo
    - NEO4J_URI=${NEO4J_URI}
    - NEO4J_USERNAME=${NEO4J_USERNAME}
    - NEO4J_PASSWORD=${NEO4J_PASSWORD}
  ports:
    - "8501:8501"
    - "8888:8888"

x-neo4j-service: &neo4j-service
  image: neo4j:5.26.6
  container_name: neo4j
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./neo4j/data:/data
  environment:
    - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

x-lightrag-service: &lightrag-service
  container_name: lightrag
  image: ghcr.io/hkuds/lightrag:1.3.9
  ports:
    - "${PORT:-9621}:9621"
  volumes:
    - ./server/rag_storage:/app/data/rag_storage
    - ./server/inputs:/app/data/inputs
    - ./server/config.ini:/app/config.ini
    - ./.env:/app/.env
  env_file:
    - .env
  environment:
    - TZ=Asia/Tokyo
    - LLM_MODEL=gpt-4.1
    - LLM_BINDING_HOST=${API_HOST}
    - LLM_BINDING_API_KEY=${API_KEY}
    - EMBEDDING_BINDING_HOST=${API_HOST}
    - EMBEDDING_BINDING_API_KEY=${API_KEY}
  restart: unless-stopped
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  app:
    <<: *app-service
    networks:
      - graphrag
  neo4j:
    <<: *neo4j-service
    networks:
      - graphrag
    profiles:
      - local
  lightrag:
    <<: *lightrag-service
    networks:
      - graphrag

networks:
  graphrag:
    driver: bridge
